"""Allow null values for hash column in messages table

Revision ID: 7b97dc3e8e4c
Revises: c00df4c8c950
Create Date: 2024-10-10 16:22:57.185265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b97dc3e8e4c'
down_revision: Union[str, None] = 'c00df4c8c950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
