"""Add WhitelistedNumber table

Revision ID: bcf635830775
Revises: d8f913cb7d2a
Create Date: 2024-09-30 17:30:50.598969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf635830775'
down_revision: Union[str, None] = 'd8f913cb7d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whitelisted_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whitelisted_numbers_id'), 'whitelisted_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_whitelisted_numbers_phone_number'), 'whitelisted_numbers', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whitelisted_numbers_phone_number'), table_name='whitelisted_numbers')
    op.drop_index(op.f('ix_whitelisted_numbers_id'), table_name='whitelisted_numbers')
    op.drop_table('whitelisted_numbers')
    # ### end Alembic commands ###
