"""Change text to encrypted_text in Message model

Revision ID: c00df4c8c950
Revises: ccc83f03b8a2
Create Date: 2024-10-10 13:43:04.824142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00df4c8c950'
down_revision: Union[str, None] = 'ccc83f03b8a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('encrypted_text', sa.LargeBinary(), nullable=True))
    op.drop_column('messages', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'encrypted_text')
    # ### end Alembic commands ###
