"""Add hash column to Message table

Revision ID: ccc83f03b8a2
Revises: 2543e62ee8d0
Create Date: 2024-10-08 12:03:43.623298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc83f03b8a2'
down_revision: Union[str, None] = '2543e62ee8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_hash'), 'messages', ['hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_hash'), table_name='messages')
    op.drop_column('messages', 'hash')
    # ### end Alembic commands ###
